[project]
name = "ai-agent-hackathon-api"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi[standard]>=0.121.2",
    "numpy>=2.3.4",
    "opencv-python>=4.11.0.86",
]
